Add libfabric support. - separated files that can be common between p4 and fabric - most of the files are skeletons with missing libfabric calls - simple test program links - configure does not work as llvm configure files need to change to add more command line options.  We can probably safely change the HEAD instead of creating a special libfabric branch.

diff --git a/runtime/libupc/configure b/runtime/libupc/configure
--- a/runtime/libupc/configure
+++ b/runtime/libupc/configure
@@ -806,6 +806,7 @@ PATH_TO_GDB
 LIBUPC_ENABLE_AFFINITY
 LIBUPC_ENABLE_NUMA
 LIBUPC_PORTALS4
+LIBUPC_FABRIC
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1483,8 +1484,8 @@ Optional Features:
   --enable-upc-gum-debug  enable UPC's source level debugging with GDB and GUM
                           support (requires UPC aware GDB)
   --enable-upc-runtime-triggered-ops
-                          Enable UPC runtime support for Portals4 triggered
-                          operations [default=yes]
+                          Enable UPC runtime support for triggered operations
+                          [default=yes]
   --enable-upc-node-local-mem
                           Enable UPC runtime support for accessing shared
                           memory of the node local threads [default=yes]
@@ -1524,7 +1525,8 @@ Optional Packages:
   --with-upc-runtime=MODEL
                           Specify the runtime implementation model for UPC,
                           where MODEL may be: 'SMP' (Symmetric
-                          Multiprocessing) or 'Portals4'. [default='SMP']
+                          Multiprocessing), 'Portals4', or "Fabric'.
+                          [default='SMP']
   --with-upc-runtime-tree-fanout=WIDTH
                           Specify the maximum number of children in each
                           sub-tree used to implement UPC collectives
@@ -1535,17 +1537,13 @@ Optional Packages:
   --with-upc-backtrace-signal=SIGNAL
                           Specify the signal to be used for UPC stack
                           backtrace [default='SIGUSR1']
-  --with-upc-runtime-max-locks=MAX_LOCKS
-                          specify the maximum number of locks that can be held
-                          by a single UPC thread [default=1024]
   --with-portals4=PATH    Specify prefix directory for installed portals4
                           package
   --with-upc-runtime-pte-base=BASE
                           Specify the base index of the first Portals4 PTE
                           used by the UPC runtime [default=16]
-  --with-upc-runtime-max-locks=MAX_LOCKS
-                          Specify the maximum number of locks that can be held
-                          by a single UPC thread [default=1024]
+  --with-fabric=PATH      Specify prefix directory for installed libfabric
+                          package
   --with-upc-runtime-bounce-buffer-size=SIZE
                           Specify the size (in bytes) of the bounce buffer
                           that is used by the UPC runtime to buffer network
@@ -1556,9 +1554,12 @@ Optional Packages:
   --with-upc-node-local-mem=SHMEM
                           Specify type of shared memory used for node local
                           memory accesses (posix or mmap) [default=posix]
-  --with-upc-job-launcher Select UPC Portals4 job launcher [default=slurm]
+  --with-upc-job-launcher Select UPC job launcher [default=slurm]
   --with-upc-memory-page-size
                           Select target memory page size [default=4096]
+  --with-upc-runtime-max-locks=MAX_LOCKS
+                          specify the maximum number of locks that can be held
+                          by a single UPC thread [default=1024]
 
 Some influential environment variables:
   CC          C compiler command
@@ -10558,7 +10559,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10561 "configure"
+#line 10562 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22133,6 +22134,9 @@ if test "${with_upc_runtime+set}" = set; then
     [Pp][Oo][Rr][Tt][Aa][Ll][Ss]4)
       upc_runtime_model=portals4
       ;;
+    [Ff][Aa][Bb][Rr][Ii][Cc])
+      upc_runtime_model=fabric
+      ;;
     *)
       { { echo "$as_me:$LINENO: error: $withval is an invalid runtime model for
       --with-upc-runtime" >&5
@@ -23195,36 +23199,6 @@ _ACEOF
   # Use the generic (reference implementation)
   use_generic_collectives="yes"
 
-  { echo "$as_me:$LINENO: checking for UPC runtime maximum number of locks held per thread" >&5
-echo $ECHO_N "checking for UPC runtime maximum number of locks held per thread... $ECHO_C" >&6; }
-
-# Check whether --with-upc-runtime-max-locks was given.
-if test "${with_upc_runtime_max_locks+set}" = set; then
-  withval=$with_upc_runtime_max_locks;
-    # $withval must be a decimal integer
-    if ! echo "$withval" | grep '^[0-9][0-9]*$' >/dev/null 2>&1; then
-      { { echo "$as_me:$LINENO: error: $withval is an invalid option to
-      --with-upc-runtime-max-locks" >&5
-echo "$as_me: error: $withval is an invalid option to
-      --with-upc-runtime-max-locks" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    upc_runtime_max_locks="$withval"
-
-else
-
-    upc_runtime_max_locks=1024
-
-fi
-
-  { echo "$as_me:$LINENO: result: $upc_runtime_max_locks" >&5
-echo "${ECHO_T}$upc_runtime_max_locks" >&6; }
-
-cat >>confdefs.h <<_ACEOF
-#define GUPCR_MAX_LOCKS $upc_runtime_max_locks
-_ACEOF
-
-
 fi #### End: SMP runtime configuration
 
 if test "$upc_runtime_model" = "portals4"; then
@@ -23461,36 +23435,221 @@ cat >>confdefs.h <<_ACEOF
 #define GUPCR_PTE_BASE $upc_runtime_pte_base
 _ACEOF
 
+fi
 
-  { echo "$as_me:$LINENO: checking for UPC runtime maximum number of locks held per thread" >&5
-echo $ECHO_N "checking for UPC runtime maximum number of locks held per thread... $ECHO_C" >&6; }
+if test "$upc_runtime_model" = "fabric"; then
 
-# Check whether --with-upc-runtime-max-locks was given.
-if test "${with_upc_runtime_max_locks+set}" = set; then
-  withval=$with_upc_runtime_max_locks;
-    # $withval must be a decimal integer
-    if ! echo "$withval" | grep '^[0-9][0-9]*$' >/dev/null 2>&1; then
-      { { echo "$as_me:$LINENO: error: $withval is an invalid option to
-      --with-upc-runtime-max-locks" >&5
-echo "$as_me: error: $withval is an invalid option to
-      --with-upc-runtime-max-locks" >&2;}
+  #### Fabric runtime library configuration ####
+
+  # Use the generic (reference implementation)
+  use_generic_collectives="no"
+
+
+for ac_header in fabric.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to bugs@yourdomain ##
+## ------------------------------ ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ have_fabric=yes
+else
+  have_fabric=no
+fi
+
+done
+
+
+# Check whether --with-fabric was given.
+if test "${with_fabric+set}" = set; then
+  withval=$with_fabric;
+    if test -f "$withval/include/rdma/fabric.h"; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_FABRIC "$withval"
+_ACEOF
+
+      LIBUPC_FABRIC=$withval
+
+    else
+      { { echo "$as_me:$LINENO: error: --with-fabric specifies wrong prefix for Libfabric package." >&5
+echo "$as_me: error: --with-fabric specifies wrong prefix for Libfabric package." >&2;}
    { (exit 1); exit 1; }; }
     fi
-    upc_runtime_max_locks="$withval"
 
 else
 
-    upc_runtime_max_locks=1024
+    if test "$have_fabric" = "no"; then
+      { { echo "$as_me:$LINENO: error: Libfabric not found - use --with-fabric to specify one." >&5
+echo "$as_me: error: Libfabric not found - use --with-fabric to specify one." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
 
 fi
 
-  { echo "$as_me:$LINENO: result: $upc_runtime_max_locks" >&5
-echo "${ECHO_T}$upc_runtime_max_locks" >&6; }
 
-cat >>confdefs.h <<_ACEOF
-#define GUPCR_MAX_LOCKS $upc_runtime_max_locks
-_ACEOF
+fi #### End: Fabric configuration
 
+if test "$upc_runtime_model" = "portals4" &&
+   test "$upc_runtime_model" = "fabric"; then
+
+  #### Infiniband based runtime library configuration ####
 
   { echo "$as_me:$LINENO: checking for UPC runtime bounce buffer size" >&5
 echo $ECHO_N "checking for UPC runtime bounce buffer size... $ECHO_C" >&6; }
@@ -23555,8 +23714,8 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-  { echo "$as_me:$LINENO: checking for UPC runtime Portals4 triggered operation support" >&5
-echo $ECHO_N "checking for UPC runtime Portals4 triggered operation support... $ECHO_C" >&6; }
+  { echo "$as_me:$LINENO: checking for UPC runtime triggered operation support" >&5
+echo $ECHO_N "checking for UPC runtime triggered operation support... $ECHO_C" >&6; }
   # Check whether --enable-upc-runtime-triggered-ops was given.
 if test "${enable_upc_runtime_triggered_ops+set}" = set; then
   enableval=$enable_upc_runtime_triggered_ops;
@@ -23579,12 +23738,12 @@ echo "${ECHO_T}$enable_upc_runtime_triggered_ops" >&6; }
   if test "$enable_upc_runtime_triggered_ops" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
-#define GUPCR_USE_PORTALS4_TRIGGERED_OPS 1
+#define GUPCR_USE_TRIGGERED_OPS 1
 _ACEOF
 
   fi
 
-# Portals4 node local memory optimization
+  # Node local memory optimization
 
   { echo "$as_me:$LINENO: checking for UPC runtime node local memory access" >&5
 echo $ECHO_N "checking for UPC runtime node local memory access... $ECHO_C" >&6; }
@@ -23834,7 +23993,7 @@ _ACEOF
     # END - check for shared memory type
   fi
 
-  # Check for portals job launcher
+  # Check for job launcher
   if test "${ac_cv_header_slurm_slurm_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for slurm/slurm.h" >&5
 echo $ECHO_N "checking for slurm/slurm.h... $ECHO_C" >&6; }
@@ -23996,8 +24155,8 @@ else
 fi
 
 
-  { echo "$as_me:$LINENO: checking for UPC runtime Portals4 job launcher" >&5
-echo $ECHO_N "checking for UPC runtime Portals4 job launcher... $ECHO_C" >&6; }
+  { echo "$as_me:$LINENO: checking for UPC runtime job launcher" >&5
+echo $ECHO_N "checking for UPC runtime job launcher... $ECHO_C" >&6; }
 
 # Check whether --with-upc-job-launcher was given.
 if test "${with_upc_job_launcher+set}" = set; then
@@ -24032,7 +24191,6 @@ cat >>confdefs.h <<\_ACEOF
 #define GUPCR_JOB_LAUNCHER_SLURM 1
 _ACEOF
 
-      portals4libs="$portals4libs -lpmi"
     else
       { { echo "$as_me:$LINENO: error: --with-upc-job-launcher specified slurm,
                     but slurm is not available." >&5
@@ -24046,37 +24204,7 @@ cat >>confdefs.h <<\_ACEOF
 #define GUPCR_JOB_LAUNCHER_YOD 1
 _ACEOF
 
-    portals4libs="$portals4libs -lportals_runtime"
   fi
-
-  # Check for target memory page size
-  { echo "$as_me:$LINENO: checking for memory page size" >&5
-echo $ECHO_N "checking for memory page size... $ECHO_C" >&6; }
-
-# Check whether --with-upc-memory-page-size was given.
-if test "${with_upc_memory_page_size+set}" = set; then
-  withval=$with_upc_memory_page_size;
-    # $withval must be a decimal integer
-    if ! echo "$withval" | grep '^[0-9][0-9]*$' >/dev/null 2>&1; then
-      { { echo "$as_me:$LINENO: error: $withval is an invalid option to --with-upc-memory-page-size" >&5
-echo "$as_me: error: $withval is an invalid option to --with-upc-memory-page-size" >&2;}
-   { (exit 1); exit 1; }; }
-    fi
-    memory_page_size="$withval"
-
-else
-
-    memory_page_size="4096"
-
-fi
-
-  { echo "$as_me:$LINENO: result: $memory_page_size" >&5
-echo "${ECHO_T}$memory_page_size" >&6; }
-
-cat >>confdefs.h <<_ACEOF
-#define GUPCR_MEMORY_PAGE_SIZE $memory_page_size
-_ACEOF
-
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -24084,7 +24212,66 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-fi #### End: Portals4 runtime configuration
+fi #### End: Infiniband based runtime configuration
+
+# Check for target memory page size
+{ echo "$as_me:$LINENO: checking for memory page size" >&5
+echo $ECHO_N "checking for memory page size... $ECHO_C" >&6; }
+
+# Check whether --with-upc-memory-page-size was given.
+if test "${with_upc_memory_page_size+set}" = set; then
+  withval=$with_upc_memory_page_size;
+  # $withval must be a decimal integer
+  if ! echo "$withval" | grep '^[0-9][0-9]*$' >/dev/null 2>&1; then
+    { { echo "$as_me:$LINENO: error: $withval is an invalid option to --with-upc-memory-page-size" >&5
+echo "$as_me: error: $withval is an invalid option to --with-upc-memory-page-size" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  memory_page_size="$withval"
+
+else
+
+  memory_page_size="4096"
+
+fi
+
+{ echo "$as_me:$LINENO: result: $memory_page_size" >&5
+echo "${ECHO_T}$memory_page_size" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define GUPCR_MEMORY_PAGE_SIZE $memory_page_size
+_ACEOF
+
+
+{ echo "$as_me:$LINENO: checking for UPC runtime maximum number of locks held per thread" >&5
+echo $ECHO_N "checking for UPC runtime maximum number of locks held per thread... $ECHO_C" >&6; }
+
+# Check whether --with-upc-runtime-max-locks was given.
+if test "${with_upc_runtime_max_locks+set}" = set; then
+  withval=$with_upc_runtime_max_locks;
+  # $withval must be a decimal integer
+  if ! echo "$withval" | grep '^[0-9][0-9]*$' >/dev/null 2>&1; then
+    { { echo "$as_me:$LINENO: error: $withval is an invalid option to
+    --with-upc-runtime-max-locks" >&5
+echo "$as_me: error: $withval is an invalid option to
+    --with-upc-runtime-max-locks" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  upc_runtime_max_locks="$withval"
+
+else
+
+  upc_runtime_max_locks=1024
+
+fi
+
+{ echo "$as_me:$LINENO: result: $upc_runtime_max_locks" >&5
+echo "${ECHO_T}$upc_runtime_max_locks" >&6; }
+
+cat >>confdefs.h <<_ACEOF
+#define GUPCR_MAX_LOCKS $upc_runtime_max_locks
+_ACEOF
+
 
 
 
@@ -25020,11 +25207,12 @@ PATH_TO_GDB!$PATH_TO_GDB$ac_delim
 LIBUPC_ENABLE_AFFINITY!$LIBUPC_ENABLE_AFFINITY$ac_delim
 LIBUPC_ENABLE_NUMA!$LIBUPC_ENABLE_NUMA$ac_delim
 LIBUPC_PORTALS4!$LIBUPC_PORTALS4$ac_delim
+LIBUPC_FABRIC!$LIBUPC_FABRIC$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 15; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
