Add configuration/Makefile for UPC backtrace on systems that require execinfo library (BSD).

diff --git a/runtime/libupc/configure b/runtime/libupc/configure
--- a/runtime/libupc/configure
+++ b/runtime/libupc/configure
@@ -801,6 +801,8 @@ GUPCR_PTS_ALIGN
 LIBUPC_RUNTIME_MODEL
 enable_upc_runtime_debug
 LIBUPC_LINK_SCRIPT
+LIBUPC_EXECINFO_LIB_PATH
+LIBUPC_EXECINFO_INC_PATH
 LIBUPC_ENABLE_BACKTRACE
 PATH_TO_GDB
 LIBGUPC_SMP_RUNTIME_TRUE
@@ -1535,20 +1537,24 @@ Optional Packages:
   --with-oprofile=<prefix>
                           Tell OProfile >= 0.9.4 how to symbolize JIT output
   --with-upc-pts          UPC packed or struct pointer representation.
-  --with-upc-pt-packed-bits
+  --with-upc-pts-packed-bits
                           Choose bit distribution in packed UPC
                           pointer-to-shared representation
   --with-upc-pts-vaddr-order
                           Choose position of the address field in UPC
                           pointer-to-shared representation
   --with-upc-runtime=MODEL
-                          specify the runtime implementation model for UPC,
+                          Specify the runtime implementation model for UPC,
                           where MODEL may be: 'SMP' (Symmetric
                           Multiprocessing) or 'Portals4'. [default='SMP']
   --with-upc-runtime-tree-fanout=WIDTH
                           Specify the maximum number of children in each
                           sub-tree used to implement UPC collectives
                           operations (e. g. upc_barrier) [default=4]
+  --with-execinfo-lib-path
+                          Specify path for execinfo library
+  --with-execinfo-inc-path
+                          Specify path for execinfo include
   --with-upc-backtrace-gdb=GDB
                           Specify which GDB to use for UPC backtrace support
                           [default='gdb']
@@ -10576,7 +10582,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10579 "configure"
+#line 10585 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21782,7 +21788,7 @@ echo "$as_me: error: --with-upc-pts-packed-bits=phase,thread,vaddr requires
     fi
 
 cat >>confdefs.h <<_ACEOF
-#define UPC_PACKED_BITS "$withval"
+#define UPC_PTS_PACKED_BITS "$withval"
 _ACEOF
 
   else
@@ -21813,7 +21819,7 @@ fi
   upc_vaddr_order=$withval
 
 cat >>confdefs.h <<_ACEOF
-#define UPC_PTS_VADDR_ORDER "$withval"
+#define UPC_VADDR_ORDER "$withval"
 _ACEOF
 
 
@@ -22370,6 +22376,127 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+
+# Check whether --with-execinfo-lib-path was given.
+if test "${with_execinfo_lib_path+set}" = set; then
+  withval=$with_execinfo_lib_path;
+else
+  withval=none
+fi
+
+{ echo "$as_me:$LINENO: checking execinfo lib path" >&5
+echo $ECHO_N "checking execinfo lib path... $ECHO_C" >&6; }
+case "$withval" in
+  none) ;;
+  *)
+     execinfo_lib_path="$withval" ;;
+esac
+{ echo "$as_me:$LINENO: result: $execinfo_lib_path" >&5
+echo "${ECHO_T}$execinfo_lib_path" >&6; }
+
+
+# Check whether --with-execinfo-inc-path was given.
+if test "${with_execinfo_inc_path+set}" = set; then
+  withval=$with_execinfo_inc_path;
+else
+  withval=none
+fi
+
+{ echo "$as_me:$LINENO: checking execinfo inc path" >&5
+echo $ECHO_N "checking execinfo inc path... $ECHO_C" >&6; }
+case "$withval" in
+  none) ;;
+  *)
+     execinfo_inc_path="$withval" ;;
+esac
+{ echo "$as_me:$LINENO: result: $execinfo_inc_path" >&5
+echo "${ECHO_T}$execinfo_inc_path" >&6; }
+
+save_CFLAGS="$CFLAGS"
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+if test "x$execinfo_inc_path" != x ; then
+  CFLAGS="$CFLAGS -I$execinfo_inc_path"
+fi
+if test "x$execinfo_lib_path" != x ; then
+  CFLAGS="$CFLAGS -L$execinfo_lib_path"
+fi
+case "$llvm_cv_os_type" in
+  FreeBSD|OpenBSD|NetBSD) CFLAGS="$CFLAGS -lexecinfo" ;;
+  *) ;;
+esac
+cat >conftest.$ac_ext <<_ACEOF
+
+  /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <execinfo.h>
+    int main () {
+      void *p;
+      return backtrace(&p, 1);
+    }
+
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_backtrace=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	have_backtrace=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+CFLAGS="$save_CFLAGS"
+
 { echo "$as_me:$LINENO: checking for UPC backtrace support" >&5
 echo $ECHO_N "checking for UPC backtrace support... $ECHO_C" >&6; }
 # Check whether --enable-upc-backtrace was given.
@@ -22389,16 +22516,37 @@ else
 
 fi
 
-{ echo "$as_me:$LINENO: result: $enable_upc_backtrace" >&5
-echo "${ECHO_T}$enable_upc_backtrace" >&6; }
-if test "$enable_upc_backtrace" = yes; then
+if test "x$enable_upc_backtrace" = xyes &&
+   test "x$have_backtrace" = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_UPC_BACKTRACE 1
 _ACEOF
 
   LIBUPC_ENABLE_BACKTRACE=1
+  if test "x$execinfo_lib_path" != x ; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_EXECINFO_LIB_PATH "$execinfo_lib_path"
+_ACEOF
+
+    LIBUPC_EXECINFO_LIB_PATH=$execinfo_lib_path
+
+  fi
+  if test "x$execinfo_inc_path" != x ; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_EXECINFO_INC_PATH "$execinfo_inc_path"
+_ACEOF
+
+    LIBUPC_EXECINFO_INC_PATH=$execinfo_inc_path
+
+  fi
+else
+  enable_upc_backtrace=no
 fi
+{ echo "$as_me:$LINENO: result: $enable_upc_backtrace" >&5
+echo "${ECHO_T}$enable_upc_backtrace" >&6; }
 
 
 # Check for user specified GDB
@@ -24658,6 +24806,8 @@ GUPCR_PTS_ALIGN!$GUPCR_PTS_ALIGN$ac_delim
 LIBUPC_RUNTIME_MODEL!$LIBUPC_RUNTIME_MODEL$ac_delim
 enable_upc_runtime_debug!$enable_upc_runtime_debug$ac_delim
 LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
+LIBUPC_EXECINFO_LIB_PATH!$LIBUPC_EXECINFO_LIB_PATH$ac_delim
+LIBUPC_EXECINFO_INC_PATH!$LIBUPC_EXECINFO_INC_PATH$ac_delim
 LIBUPC_ENABLE_BACKTRACE!$LIBUPC_ENABLE_BACKTRACE$ac_delim
 PATH_TO_GDB!$PATH_TO_GDB$ac_delim
 LIBGUPC_SMP_RUNTIME_TRUE!$LIBGUPC_SMP_RUNTIME_TRUE$ac_delim
@@ -24690,7 +24840,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
