Add portals4 include path on the libupc runtime compile line. In the past we had it as part of the driver, which is not the case any more.

diff --git a/runtime/libupc/configure b/runtime/libupc/configure
--- a/runtime/libupc/configure
+++ b/runtime/libupc/configure
@@ -803,6 +803,7 @@ enable_upc_runtime_debug
 LIBUPC_LINK_SCRIPT
 LIBUPC_ENABLE_BACKTRACE
 PATH_TO_GDB
+LIBUPC_PORTALS4
 LIBGUPC_SMP_RUNTIME_TRUE
 LIBGUPC_SMP_RUNTIME_FALSE
 LIBGUPC_PORTALS4_RUNTIME_TRUE
@@ -1535,14 +1536,14 @@ Optional Packages:
   --with-oprofile=<prefix>
                           Tell OProfile >= 0.9.4 how to symbolize JIT output
   --with-upc-pts          UPC packed or struct pointer representation.
-  --with-upc-pt-packed-bits
+  --with-upc-pts-packed-bits
                           Choose bit distribution in packed UPC
                           pointer-to-shared representation
   --with-upc-pts-vaddr-order
                           Choose position of the address field in UPC
                           pointer-to-shared representation
   --with-upc-runtime=MODEL
-                          specify the runtime implementation model for UPC,
+                          Specify the runtime implementation model for UPC,
                           where MODEL may be: 'SMP' (Symmetric
                           Multiprocessing) or 'Portals4'. [default='SMP']
   --with-upc-runtime-tree-fanout=WIDTH
@@ -1558,6 +1559,8 @@ Optional Packages:
   --with-upc-runtime-max-locks=MAX_LOCKS
                           specify the maximum number of locks that can be held
                           by a single UPC thread [default=1024]
+  --with-portals4=PATH    Specify prefix directory for installed portals4
+                          package
   --with-upc-runtime-pte-base=BASE
                           Specify the base index of the first Portals4 PTE
                           used by the UPC runtime [default=16]
@@ -10576,7 +10579,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10579 "configure"
+#line 10582 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21782,7 +21785,7 @@ echo "$as_me: error: --with-upc-pts-packed-bits=phase,thread,vaddr requires
     fi
 
 cat >>confdefs.h <<_ACEOF
-#define UPC_PACKED_BITS "$withval"
+#define UPC_PTS_PACKED_BITS "$withval"
 _ACEOF
 
   else
@@ -21813,7 +21816,7 @@ fi
   upc_vaddr_order=$withval
 
 cat >>confdefs.h <<_ACEOF
-#define UPC_PTS_VADDR_ORDER "$withval"
+#define UPC_VADDR_ORDER "$withval"
 _ACEOF
 
 
@@ -22834,6 +22837,206 @@ if test "$upc_runtime_model" = "portals4"; then
 
   # Use the generic (reference implementation)
   use_generic_collectives="no"
+
+
+for ac_header in portals4.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------ ##
+## Report this to bugs@yourdomain ##
+## ------------------------------ ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ have_p4=yes
+else
+  have_p4=no
+fi
+
+done
+
+
+# Check whether --with-portals4 was given.
+if test "${with_portals4+set}" = set; then
+  withval=$with_portals4;
+    if test -f "$withval/include/portals4.h"; then
+
+cat >>confdefs.h <<_ACEOF
+#define LIBUPC_PORTALS4 "$withval"
+_ACEOF
+
+      LIBUPC_PORTALS4=$withval
+
+    else
+      { { echo "$as_me:$LINENO: error: --with-portals4 specifies wrong prefix for Portals4 package." >&5
+echo "$as_me: error: --with-portals4 specifies wrong prefix for Portals4 package." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+else
+
+    if test "$have_p4" = "no"; then
+      { { echo "$as_me:$LINENO: error: Portals4 not found - use --with-portals4 to specify one." >&5
+echo "$as_me: error: Portals4 not found - use --with-portals4 to specify one." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+fi
+
 
   { echo "$as_me:$LINENO: checking for UPC runtime Portals4 PTE base index" >&5
 echo $ECHO_N "checking for UPC runtime Portals4 PTE base index... $ECHO_C" >&6; }
@@ -24660,6 +24863,7 @@ enable_upc_runtime_debug!$enable_upc_runtime_debug$ac_delim
 LIBUPC_LINK_SCRIPT!$LIBUPC_LINK_SCRIPT$ac_delim
 LIBUPC_ENABLE_BACKTRACE!$LIBUPC_ENABLE_BACKTRACE$ac_delim
 PATH_TO_GDB!$PATH_TO_GDB$ac_delim
+LIBUPC_PORTALS4!$LIBUPC_PORTALS4$ac_delim
 LIBGUPC_SMP_RUNTIME_TRUE!$LIBGUPC_SMP_RUNTIME_TRUE$ac_delim
 LIBGUPC_SMP_RUNTIME_FALSE!$LIBGUPC_SMP_RUNTIME_FALSE$ac_delim
 LIBGUPC_PORTALS4_RUNTIME_TRUE!$LIBGUPC_PORTALS4_RUNTIME_TRUE$ac_delim
@@ -24690,7 +24894,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
